[[redirects]]
    from = "/ucode-com/*"
    to = "https://ucode.com/:splat"

[[redirects]]
    from = "/senreve-com/*"
    to = "https://senreve.com/:splat"

[[redirects]]
    from = "/doelashes-com/*"
    to = "https://doelashes.com/:splat"
