[[headers]]
    for = "/.well-known/amphtml/apikey.pub"
    [headers.values]
        Content-Type = "text/plain"

[[redirects]]
    from = "/amp/index.html"
    to = "https://diathrive.com/"

[[redirects]]
    from = "/amp/*"
    to = "https://diathrive.com/:splat"
    
[[redirects]]
    from = "/*"
    to = "https://diathrive.com/:splat"
